# Generated by Django 3.2.7 on 2021-09-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名前')),
                ('affiliation', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='youtubeURL')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
            ],
        ),
    ]
